import { codeToHtml } from 'shiki';
import { writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
// Go up from scripts/ to web package root
const outputPath = resolve(__dirname, '..', 'home-code-blocks.ts');

const installCode = await codeToHtml('pnpm add delta-agents', {
  lang: 'bash',
  theme: 'material-theme-ocean',
});

const actionCode = await codeToHtml(`import { Ok } from "delta-agents";
import { z } from "zod";

const issueRefund = delta.action({
  name: "issue-refund",
  description: "Issue a refund for an order",
  risk: 4,
  requiresApproval: true,
  schema: z.object({
    orderId: z.string(),
    amount: z.number().positive(),
  }),
  fn: async ({ orderId, amount }) => {
    const receipt = await refundOrder(orderId, amount);
    return Ok(receipt);
  },
});`, {
  lang: 'typescript',
  theme: 'material-theme-ocean',
});

const serviceCode = await codeToHtml(`const supportAgent = delta.agent({
  name: "support-agent",
  description: "Handles order support requests",
  role: "Order Support Specialist",
  rolePrompt: "Look up the order, then decide whether a refund is warranted.",
  actions: [lookupOrder, issueRefund],
});

delta.deploy(supportAgent);`, {
  lang: 'typescript',
  theme: 'material-theme-ocean',
});

const serverCode = await codeToHtml(`const result = await delta.send({
  goal: "Look up order ORD-1042 and refund the customer",
  agentName: "support-agent",
  budget: { tokens: 5000, durationMs: 30_000 },
});

// result.value.status -> "blocked" (refund needs a human sign-off)`, {
  lang: 'typescript',
  theme: 'material-theme-ocean',
});

const invokeCode = await codeToHtml(`const inspection = await delta.inspect(result.value.taskId);
const pending = inspection.value.pendingApprovals[0];

await delta.approve(pending.id);
const resumed = await delta.resume(result.value.taskId);

// resumed.value.status -> "completed"`, {
  lang: 'typescript',
  theme: 'material-theme-ocean',
});

// Also export the raw strings for copy buttons
const installRaw = 'pnpm add delta-agents';

const actionRaw = `import { Ok } from "delta-agents";
import { z } from "zod";

const issueRefund = delta.action({
  name: "issue-refund",
  description: "Issue a refund for an order",
  risk: 4,
  requiresApproval: true,
  schema: z.object({
    orderId: z.string(),
    amount: z.number().positive(),
  }),
  fn: async ({ orderId, amount }) => {
    const receipt = await refundOrder(orderId, amount);
    return Ok(receipt);
  },
});`;

const serviceRaw = `const supportAgent = delta.agent({
  name: "support-agent",
  description: "Handles order support requests",
  role: "Order Support Specialist",
  rolePrompt: "Look up the order, then decide whether a refund is warranted.",
  actions: [lookupOrder, issueRefund],
});

delta.deploy(supportAgent);`;

const serverRaw = `const result = await delta.send({
  goal: "Look up order ORD-1042 and refund the customer",
  agentName: "support-agent",
  budget: { tokens: 5000, durationMs: 30_000 },
});

// result.value.status -> "blocked" (refund needs a human sign-off)`;

const invokeRaw = `const inspection = await delta.inspect(result.value.taskId);
const pending = inspection.value.pendingApprovals[0];

await delta.approve(pending.id);
const resumed = await delta.resume(result.value.taskId);

// resumed.value.status -> "completed"`;

const content = `// Auto-generated by scripts/generate-home-code.ts
// Do not edit manually

export const installCode = ${JSON.stringify(installCode)};
export const actionCode = ${JSON.stringify(actionCode)};
export const serviceCode = ${JSON.stringify(serviceCode)};
export const serverCode = ${JSON.stringify(serverCode)};
export const invokeCode = ${JSON.stringify(invokeCode)};

export const installRaw = ${JSON.stringify(installRaw)};
export const actionRaw = ${JSON.stringify(actionRaw)};
export const serviceRaw = ${JSON.stringify(serviceRaw)};
export const serverRaw = ${JSON.stringify(serverRaw)};
export const invokeRaw = ${JSON.stringify(invokeRaw)};
`;

await writeFile(outputPath, content);
console.log('Generated home code blocks at', outputPath);
